services:
  classificador:
    build: .
    volumes:
      - type: bind
        source: 'Datasets_LISA:\datasets_covid\covidxct'
        target: /app/data
      - ./outputs:/app/outputs      # Outputs gerados (gráficos, métricas)

    environment:
      - DATASET_PATH=/app/data      # Caminho do dataset dentro do contêiner

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]